
name: Build docs
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: install xelatex
        run: sudo apt-get install texlive-full
      - name: Compose the CV
        run: make
        

      
